//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by spehon32.rc
//
#define IDD_SPOOLSPY                    101
#define IDI_COLIVE                      102
#define IDR_MAIN                        103
#define IDC_LINE1                       1000
#define IDC_LINE2                       1001
#define IDC_LINE3                       1002
#define IDC_LINE4                       1003
#define IDC_MIDVIEW                     1008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
